SerpentStream: SerpentStream.cpp SerpentCounter.cpp
	g++ -std=c++0x -c -o SerpentCounter.o SerpentCounter.cpp
	g++ -std=c++0x -c -o SerpentStream.o SerpentStream.cpp  
	g++ -std=c++0x -o SerpentStream SerpentCounter.o SerpentStream.o